"""SLASH baseline on MNIST add/3 (distant supervision) with generative
evaluation.

Adapted from src/experiments/mnist_generative/train.py of the official
SLASH repository (https://github.com/askrix/SLASH, Skryagin et al.,
KR 2022 / JAIR 2023). The neural-probabilistic predicate is an
EinsumNetwork probabilistic circuit (Poon-Domingos structure) over the
784 pixels, trained by alternating EM log-likelihood maximisation with
SLASH's ASP-based distant-supervision step, exactly as in their
generative-learning experiment. Digit images are generated by
class-conditional sampling from the circuit, which is the generative
mode demonstrated in their paper.

Generative accuracy uses the same 1-nearest-neighbour oracle as the
Declarative DeepProbLog experiments.

Usage:
    python run_mnist_slash.py --epochs 5 --seed 0
"""
import argparse
import csv
import random
import sys
import time
from pathlib import Path

import numpy as np
import torch
import torchvision
from torchvision.transforms import transforms

_HERE = Path(__file__).parent
_SRC = _HERE.parent / "slash_src"
sys.path.insert(0, str(_SRC))
sys.path.insert(0, str(_SRC / "SLASH"))

from einsum_wrapper import EiNet
from EinsumNetwork import EinsumNetwork
from EinsumNetwork.FactorizedLeafLayer import FactorizedLeafLayer
from EinsumNetwork.SumLayer import SumLayer
from slash import SLASH

_DATA_ROOT = _HERE.parent.parent / "deepproblog_examples" / "MNIST" / "data"

# Program from the official mnist_addition experiment. The mnist_generative
# experiment's variant (digit(0,+A,-N1), digit(0,+B,+N2), A != B, with the
# observation addition(i1,_,l)) did not converge in our runs (digit accuracy
# plateaued at ~19%), so we combine the canonical addition program with the
# generative EM interleave of the mnist_generative experiment.
PROGRAM = """
img(i1). img(i2).
addition(A,B,N):- digit(0,+A,-N1), digit(0,+B,-N2), N=N1+N2.
npp(digit(1,X), [0,1,2,3,4,5,6,7,8,9]) :- img(X).
"""

# direct supervision on single digits
PROGRAM_DIGIT = """
img(i1).
digitpred(N) :- digit(0,+A,-N), img(A).
npp(digit(1,X), [0,1,2,3,4,5,6,7,8,9]) :- img(X).
"""

MEAN, STD = 0.1307, 0.3081
transform = transforms.Compose(
    [transforms.ToTensor(), transforms.Normalize((MEAN,), (STD,)),
     transforms.Lambda(lambda x: torch.flatten(x))]
)


class DigitDataset(torch.utils.data.Dataset):
    def __init__(self, dataset, seed, data_size=None):
        indices = list(range(len(dataset)))
        random.Random(seed).shuffle(indices)
        if data_size is not None:
            indices = indices[:data_size]
        self.indices = indices
        self.dataset = dataset

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, index):
        i = self.indices[index]
        return ({"i1": self.dataset[i][0]},
                ":- not digitpred({}).".format(self.dataset[i][1]))


class PairDataset(torch.utils.data.Dataset):
    def __init__(self, dataset, seed, data_size=None):
        indices = list(range(len(dataset)))
        random.Random(seed).shuffle(indices)
        self.pairs = [(indices[2 * i], indices[2 * i + 1])
                      for i in range(len(indices) // 2)]
        if data_size is not None:
            self.pairs = self.pairs[:data_size]
        self.dataset = dataset

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, index):
        i, j = self.pairs[index]
        label = self.dataset[i][1] + self.dataset[j][1]
        obs = ":- not addition(i1, i2, {}).".format(label)
        return {"i1": self.dataset[i][0], "i2": self.dataset[j][0]}, obs


# --- EM/GD domain switching ---
# The official experiment's complient_with_em clamps GD-domain parameters at
# 1e-16 before renormalising. GD-domain sum weights are the *logarithms* of
# the weights used at inference time (reparam is a softmax), so the clamp
# maps every weight to (near-)uniform and erases each epoch's SLASH step; it
# likewise feeds GD-encoded leaf parameters to project_params, which expects
# expectation parameters. We replace both directions with the mathematically
# exact conversions so that the alternation preserves the learned model
# (documented in the README; the vendored SLASH sources are unmodified).

def complient_with_em(einet):
    """GD domain -> EM domain: apply the same reparametrisations the GD
    forward pass uses, yielding valid EM parameters."""
    with torch.no_grad():
        for layer in einet.einet_layers:
            if issubclass(type(layer), SumLayer):
                p = layer.params
                lse = torch.logsumexp(p, dim=layer.normalization_dims, keepdim=True)
                layer.params.data = (p - lse).exp()
                if layer.params_mask is not None:
                    layer.params.data *= layer.params_mask
                layer.params.data = layer.params / (
                    layer.params.sum(layer.normalization_dims, keepdim=True)
                )
                layer.params.grad = None
            if issubclass(type(layer), FactorizedLeafLayer):
                ef = layer.ef_array
                ef.params.data = ef.project_params(ef.reparam(ef.params.data))


def complient_with_gd(einet):
    """EM domain -> GD domain: invert the GD reparametrisations."""
    with torch.no_grad():
        for layer in einet.einet_layers:
            if issubclass(type(layer), SumLayer):
                if layer.params_mask is not None:
                    layer.params.data *= layer.params_mask
                layer.params.data = torch.clamp(layer.params, 1e-16).log()
                layer.params.grad = None
            if issubclass(type(layer), FactorizedLeafLayer):
                ef = layer.ef_array
                nd = ef.num_dims
                phi = ef.params.data
                mu = phi[..., :nd]
                var = torch.clamp(phi[..., nd:] - mu ** 2,
                                  ef.min_var * (1 + 1e-6), ef.max_var * (1 - 1e-6))
                t = torch.clamp((var - ef.min_var) / (ef.max_var - ef.min_var),
                                1e-6, 1 - 1e-6)
                ef.params.data = torch.cat((mu, torch.log(t) - torch.log1p(-t)), -1)
                ef.params.grad = None


def einet_set_use_em(einet, use_em):
    einet.einet_layers[0].ef_array._use_em = use_em
    for layer in einet.einet_layers:
        layer._use_em = use_em


# --- evaluation ---

class NNOracle:
    """1-NN oracle in [-1, 1] pixel space over the full training set."""

    def __init__(self):
        raw = torchvision.datasets.MNIST(root=str(_DATA_ROOT), train=True)
        X = raw.data.numpy().astype("float32") / 255.0
        self.X = ((X - 0.5) / 0.5).reshape(len(X), -1)
        self.y = raw.targets.numpy()
        self.sq_norms = (self.X ** 2).sum(axis=1)

    def labels(self, generated):
        d = self.sq_norms[None, :] - 2.0 * generated @ self.X.T
        return self.y[d.argmin(axis=1)]


def to_pm1(samples):
    """PC samples live in the (0.1307, 0.3081)-normalised space; map to
    the [-1, 1] space of the oracle."""
    raw = samples * STD + MEAN
    return np.clip((raw - 0.5) / 0.5, -1.0, 1.0)


def posterior_probs(m, loader):
    m.eval()
    probs, labels = [], []
    with torch.no_grad():
        for imgs, lab in loader:
            probs.append(m(imgs).numpy())
            labels.append(lab.numpy())
    m.train()
    return np.concatenate(probs), np.concatenate(labels)


def discriminative_eval(m):
    test = torchvision.datasets.MNIST(root=str(_DATA_ROOT), train=False,
                                      transform=transform)
    loader = torch.utils.data.DataLoader(test, batch_size=100)
    probs, labels = posterior_probs(m, loader)
    digit_acc = (probs.argmax(-1) == labels).mean()
    n_pairs = len(labels) // 2
    p1, p2 = probs[0::2][:n_pairs], probs[1::2][:n_pairs]
    sum_probs = np.zeros((n_pairs, 19))
    for a in range(10):
        for b in range(10):
            sum_probs[:, a + b] += p1[:, a] * p2[:, b]
    true = labels[0::2][:n_pairs] + labels[1::2][:n_pairs]
    sum_acc = (sum_probs.argmax(-1) == true).mean()
    return digit_acc, sum_acc


def generative_eval(m, oracle, out_dir, per_class=100, pair_repeats=10):
    m.eval()
    rows, correct, total = [], 0, 0
    with torch.no_grad():
        for d in range(10):
            samples = m.sample(num_samples=per_class, class_idx=d).cpu().numpy()
            nn = oracle.labels(to_pm1(samples.reshape(-1, 784)))
            correct += (nn == d).sum()
            total += len(nn)
            rows += [[d, int(l)] for l in nn]
    gen_digit = correct / total
    with open(out_dir / "generative_digit_details.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["label", "nn_label"])
        w.writerows(rows)

    rows, correct, total = [], 0, 0
    with torch.no_grad():
        for s in range(19):
            combos = [(a, s - a) for a in range(10) if 0 <= s - a <= 9]
            for a, b in combos:
                s1 = m.sample(num_samples=pair_repeats, class_idx=a).cpu().numpy()
                s2 = m.sample(num_samples=pair_repeats, class_idx=b).cpu().numpy()
                nn1 = oracle.labels(to_pm1(s1.reshape(-1, 784)))
                nn2 = oracle.labels(to_pm1(s2.reshape(-1, 784)))
                correct += (nn1 + nn2 == s).sum()
                total += len(nn1)
                rows += [[s, int(x), int(y)] for x, y in zip(nn1, nn2)]
    gen_add = correct / total
    with open(out_dir / "generative_addition_details.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["sum", "nn_label_1", "nn_label_2"])
        w.writerows(rows)
    m.train()
    return gen_digit, gen_add


def save_sample_grid(m, path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    with torch.no_grad():
        grids = []
        for d in range(10):
            s = m.sample(num_samples=5, class_idx=d).cpu().numpy()
            grids.append(to_pm1(s.reshape(-1, 28, 28)).reshape(-1, 28))
        grid = np.concatenate(grids, axis=1)
    plt.figure(figsize=(20, 10))
    plt.imshow(grid, cmap="gray")
    plt.axis("off")
    plt.savefig(path, bbox_inches="tight", dpi=80)
    plt.close()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--epochs", type=int, default=5)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--data-size", type=int, default=None)
    parser.add_argument("--batch-size", type=int, default=100)
    parser.add_argument("--p-num", type=int, default=8)
    parser.add_argument("--em-warmup", type=int, default=5,
                        help="EM passes in the first epoch (then 1/epoch)")
    parser.add_argument("--no-em", action="store_true",
                        help="skip the EM likelihood phase entirely "
                             "(purely discriminative control run)")
    parser.add_argument("--task", choices=["addition", "digit"],
                        default="addition")
    args = parser.parse_args()

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)
    random.seed(args.seed)

    out_dir = _HERE / "results" / f"{args.task}_seed{args.seed}"
    out_dir.mkdir(parents=True, exist_ok=True)

    m = EiNet(structure="poon-domingos", pd_num_pieces=[7], use_em=False,
              num_var=784, class_count=10, pd_width=28, pd_height=28,
              learn_prior=True)
    n_params = sum(p.numel() for p in m.parameters())
    print(f"EiNet with {n_params} parameters")

    optimizers = {"digit": torch.optim.Adam(m.parameters(), lr=0.01, eps=1e-7)}
    slash_obj = SLASH(PROGRAM_DIGIT if args.task == "digit" else PROGRAM,
                      {"digit": m}, optimizers)
    ll_optimizer = torch.optim.Adam(m.parameters(), lr=0.01, eps=1e-7)

    train = torchvision.datasets.MNIST(root=str(_DATA_ROOT), train=True,
                                       download=True, transform=transform)
    dataset_cls = DigitDataset if args.task == "digit" else PairDataset
    pair_loader = torch.utils.data.DataLoader(
        dataset_cls(train, args.seed, args.data_size), shuffle=True,
        batch_size=args.batch_size, num_workers=0,
    )

    oracle = NNOracle()
    warmup = args.em_warmup
    complient_with_em(m)
    einet_set_use_em(m, True)
    m.train()

    t0 = time.time()
    history = []
    for e in range(args.epochs):
        print(f"Epoch {e + 1}...", flush=True)
        # EM log-likelihood maximisation
        for _ in range(0 if args.no_em else warmup):
            for data_batch, _ in pair_loader:
                ll_optimizer.zero_grad()
                batch_x = data_batch["i1"]
                outputs = m.get_log_likelihoods(batch_x)
                EinsumNetwork.log_likelihoods(outputs).sum().backward()
                m.em_process_batch()
            m.em_update()
        warmup = 1

        # SLASH distant-supervision step (gradient domain)
        m.train()
        complient_with_gd(m)
        einet_set_use_em(m, False)
        slash_obj.learn(dataset_loader=pair_loader, epoch=1,
                        batchSize=args.batch_size, p_num=args.p_num)

        digit_acc, sum_acc = discriminative_eval(m)
        print(f"epoch {e + 1}: digit_acc={digit_acc:.4f} sum_acc={sum_acc:.4f}",
              flush=True)
        history.append([e + 1, digit_acc, sum_acc])

        # back to EM domain
        complient_with_em(m)
        einet_set_use_em(m, True)
        m.train()
        save_sample_grid(m, out_dir / f"samples_epoch{e + 1}.png")

    train_time = time.time() - t0

    # discriminative numbers come from the last GD-domain evaluation in the
    # loop; sampling for the generative evaluation happens in the EM domain,
    # matching the official experiment
    digit_acc, sum_acc = history[-1][1], history[-1][2]
    gen_digit, gen_add = generative_eval(m, oracle, out_dir)
    print(f"final: digit_acc={digit_acc:.4f} sum_acc={sum_acc:.4f} "
          f"gen_digit={gen_digit:.4f} gen_add={gen_add:.4f} "
          f"train_time={train_time:.1f}s", flush=True)

    torch.save(m.state_dict(), out_dir / "einet.pt")
    with open(out_dir / "summary.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["seed", "epochs", "data_size", "train_time_s",
                    "class_digit_acc", "class_add_acc",
                    "gen_digit_acc", "gen_add_acc"])
        w.writerow([args.seed, args.epochs, args.data_size,
                    round(train_time, 1), digit_acc, sum_acc,
                    gen_digit, gen_add])
    with open(out_dir / "history.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["epoch", "digit_acc", "sum_acc"])
        w.writerows(history)


if __name__ == "__main__":
    main()
